name: Deploy Laravel App to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy files to cPanel via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_PRIVATE_KEY }}
          source: "./"
          target: "/home2/jididigi/bcart_backend"

      - name: Run deployment commands on cPanel
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_PRIVATE_KEY }}
          script: |
            cd /home/YOUR_CPANEL_USERNAME/public_html/YOUR_APP_DIRECTORY
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
