name: Deploy Laravel App to cPanel for bCartt

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.jidi.digital
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}

